exclude: 'build|docs|node_modules|.git|.tox|staticfiles|static_files|media_files|((?:[^/]*/)*)(.svg)|((?:[^/]*/)*)(.xml)'
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=10240']

  - repo: https://github.com/windpioneers/pre-commit-hooks
    rev: 0.0.5
    hooks:
      - id: check-branch-name
        args:
          - '^main$'
          - '^development$'
          - '^staging$'
          - '^devops/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^doc/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^feature/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^fix/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^hotfix/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^learning/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^review/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.2.1'
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.19.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: ['--fix']
        additional_dependencies:
          - babel-eslint@^10.1.0
          - eslint@^7.19.0
          - eslint-config-prettier@^8.1.0
          - eslint-loader@^4.0.2
          - eslint-plugin-flowtype@^4.7.0
          - eslint-plugin-flowtype-errors@^4.3.0
          - eslint-plugin-import@^2.22.1
          - eslint-plugin-jsx-a11y@^6.4.1
          - eslint-plugin-react@^7.20.5
          - eslint-plugin-react-hooks@^4.2.0
          - flow-bin@^0.143.1
          - prettier@^2.2.1
          - react-scripts@^4.0.3
